import { ResponseObject, ResponseToolkit } from "@hapi/hapi"
import { httpStatus } from "./httpStatus"
import { ServiceResponse } from "../interfaces/requestInterfaces"

/**
 * Sends an HTTP response using the provided `ResponseToolkit` object.
 * The function extracts the response data and status code from the `serviceResponse` 
 * and sends it back to the client.
 * 
 * @param {ResponseToolkit} res - The hapi `ResponseToolkit` used to generate the response.
 * @param {any} serviceResponse - The response object from the service, containing `data` and `status` properties.
 * 
 * @returns {ResponseObject} - The response object generated by hapi, with the appropriate status code.
 * 
 * @example
 * const serviceResponse = {
 *   data: { message: "Success" },
 *   status: 200
 * };
 * sendResponse(res, serviceResponse);
 */
export const sendResponse = (res: ResponseToolkit, serviceResponse: any): ResponseObject => {
    return res.response(serviceResponse.data).code(
        httpStatus[
            serviceResponse.status as keyof typeof httpStatus
        ] || 500
    )
}

/**
 * Sends a service response with the provided status, message, and data.
 *
 * @param {string} status - The status of the service response (e.g., 'SUCCESS', 'ERROR').
 * @param {string} message - A message describing the response (e.g., 'Operation completed successfully').
 * @param {any} data - The data to include in the response (can be any type, depending on the use case).
 * @returns {ServiceResponse} - An object containing the status, message, and data.
 */
export const sendServiceResponse = (status: string, message: string, data: any): ServiceResponse => {
    return { 
        status, 
        message, 
        data 
    }
}